import type { Metadata } from "next";
import { Schibsted_Grotesk } from "next/font/google";
import { Header } from "@/components/Header";

import "./globals.css";
import { FaGithub } from "react-icons/fa";

const schibstedGrotesk = Schibsted_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${schibstedGrotesk.className} px-16 p-4 dark:bg-[#030D13] dark:text-white`}
      >
        <main className="flex-grow container min-h-screen flex items-center justify-center">
          {children}
        </main>
      </body>
    </html>
  );
}
