import type { Metadata } from "next";
import { Schibsted_Grotesk } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const schibstedGrotesk = Schibsted_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${schibstedGrotesk.className} px-16 p-4 dark:bg-[#030D13] dark:text-white`}
      >
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow container flex items-center justify-center">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
